### ISSUE TITLE
WX Widgets CYK Visualisierung

### ISSUE THREAD

**Issue by FelixKirscht** [sewpalu/ProGramm#17]
# TODO
- [x] Bug bei leerer Worteingabe
- [ ] Das Ursprungsfeld wird bei Visualisierung der Produktionenen doppelt hervorgehoben, dafür fehlt eine der Produktionen.
- [x] STVisualisationTab crasht bei dynamischem Baum 
- [x] STVisualisationTab ist zu flach

Closed, weil Punkt 2 in CYK bugs behandelt wird
